"""empty message

Revision ID: ef3f2651440e
Revises: 
Create Date: 2023-05-02 17:53:47.883000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3f2651440e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_email_sendgrid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('templatename', sa.String(), nullable=True),
    sa.Column('templateid', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('templateid'),
    sa.UniqueConstraint('templatename')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('address_two', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state_province', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completedfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('date_completed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cwmaintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintaindate', sa.DateTime(), nullable=True),
    sa.Column('workdone', sa.String(length=500), nullable=True),
    sa.Column('partsused', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hrfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('date_of_review', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidentnumbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident', sa.String(length=100), nullable=True),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclaimtank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reclaimdate', sa.DateTime(), nullable=True),
    sa.Column('tankonewater', sa.String(length=100), nullable=True),
    sa.Column('tankonesand', sa.String(length=100), nullable=True),
    sa.Column('tanktwowater', sa.String(length=100), nullable=True),
    sa.Column('tanktwosand', sa.String(length=100), nullable=True),
    sa.Column('tanklids', sa.String(length=100), nullable=True),
    sa.Column('changepillows', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saltlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saltdate', sa.DateTime(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('gsa', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('carwash', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twimlmessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twimlname', sa.String(), nullable=True),
    sa.Column('twimlid', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twimlid'),
    sa.UniqueConstraint('twimlname')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('injuryorillness', sa.Boolean(), nullable=True),
    sa.Column('environmental', sa.Boolean(), nullable=True),
    sa.Column('regulatory', sa.Boolean(), nullable=True),
    sa.Column('economicdamage', sa.Boolean(), nullable=True),
    sa.Column('reputation', sa.Boolean(), nullable=True),
    sa.Column('security', sa.Boolean(), nullable=True),
    sa.Column('fire', sa.Boolean(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('eventdetails', sa.String(), nullable=True),
    sa.Column('eventdate', sa.DateTime(), nullable=True),
    sa.Column('eventtime', sa.Time(), nullable=True),
    sa.Column('reportedby', sa.String(), nullable=True),
    sa.Column('reportedbynumber', sa.String(), nullable=True),
    sa.Column('suncoremployee', sa.Boolean(), nullable=True),
    sa.Column('contractor', sa.Boolean(), nullable=True),
    sa.Column('associate', sa.Boolean(), nullable=True),
    sa.Column('generalpublic', sa.Boolean(), nullable=True),
    sa.Column('other', sa.Boolean(), nullable=True),
    sa.Column('othertext', sa.String(), nullable=True),
    sa.Column('actionstaken', sa.String(), nullable=True),
    sa.Column('correctiveactions', sa.String(), nullable=True),
    sa.Column('sno', sa.Boolean(), nullable=True),
    sa.Column('syes', sa.Boolean(), nullable=True),
    sa.Column('scomment', sa.String(), nullable=True),
    sa.Column('rna', sa.Boolean(), nullable=True),
    sa.Column('rno', sa.Boolean(), nullable=True),
    sa.Column('ryes', sa.Boolean(), nullable=True),
    sa.Column('rcomment', sa.String(), nullable=True),
    sa.Column('gas', sa.Boolean(), nullable=True),
    sa.Column('diesel', sa.Boolean(), nullable=True),
    sa.Column('sewage', sa.Boolean(), nullable=True),
    sa.Column('chemical', sa.Boolean(), nullable=True),
    sa.Column('chemcomment', sa.String(), nullable=True),
    sa.Column('deiselexhaustfluid', sa.Boolean(), nullable=True),
    sa.Column('sother', sa.Boolean(), nullable=True),
    sa.Column('s2comment', sa.String(), nullable=True),
    sa.Column('air', sa.Boolean(), nullable=True),
    sa.Column('water', sa.Boolean(), nullable=True),
    sa.Column('wildlife', sa.Boolean(), nullable=True),
    sa.Column('land', sa.Boolean(), nullable=True),
    sa.Column('volumerelease', sa.String(), nullable=True),
    sa.Column('pyes', sa.Boolean(), nullable=True),
    sa.Column('pno', sa.Boolean(), nullable=True),
    sa.Column('pna', sa.Boolean(), nullable=True),
    sa.Column('pcase', sa.String(), nullable=True),
    sa.Column('stolentransactions', sa.Boolean(), nullable=True),
    sa.Column('stoltransactions', sa.String(), nullable=True),
    sa.Column('stolencards', sa.Boolean(), nullable=True),
    sa.Column('stolcards', sa.String(), nullable=True),
    sa.Column('stolentobacco', sa.Boolean(), nullable=True),
    sa.Column('stoltobacco', sa.String(), nullable=True),
    sa.Column('stolenlottery', sa.Boolean(), nullable=True),
    sa.Column('stollottery', sa.String(), nullable=True),
    sa.Column('stolenfuel', sa.Boolean(), nullable=True),
    sa.Column('stolfuel', sa.String(), nullable=True),
    sa.Column('stolenother', sa.Boolean(), nullable=True),
    sa.Column('stolother', sa.String(), nullable=True),
    sa.Column('stolenothervalue', sa.String(), nullable=True),
    sa.Column('stolenna', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('haircolor', sa.String(), nullable=True),
    sa.Column('haircut', sa.String(), nullable=True),
    sa.Column('complexion', sa.String(), nullable=True),
    sa.Column('beardmoustache', sa.String(), nullable=True),
    sa.Column('eyeeyeglasses', sa.String(), nullable=True),
    sa.Column('licencenumber', sa.String(), nullable=True),
    sa.Column('makemodel', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('scars', sa.String(), nullable=True),
    sa.Column('tatoos', sa.String(), nullable=True),
    sa.Column('hat', sa.String(), nullable=True),
    sa.Column('shirt', sa.String(), nullable=True),
    sa.Column('trousers', sa.String(), nullable=True),
    sa.Column('shoes', sa.String(), nullable=True),
    sa.Column('voice', sa.String(), nullable=True),
    sa.Column('bumpersticker', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('damage', sa.String(), nullable=True),
    sa.Column('image_folder', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_store',
    sa.Column('incidentnumbers_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incidentnumbers_id'], ['incidentnumbers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], )
    )
    op.create_table('maintain_store',
    sa.Column('maintain_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maintain_id'], ['cwmaintenance.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], )
    )
    op.create_table('reclaim_store',
    sa.Column('reclaim_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reclaim_id'], ['reclaimtank.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], )
    )
    op.create_table('salt_store',
    sa.Column('saltlog_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saltlog_id'], ['saltlog.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], )
    )
    op.create_table('task_store',
    sa.Column('todo_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('checkinout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('enddate', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('check_store', sa.Integer(), nullable=True),
    sa.Column('check_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_store'], ['store.id'], ),
    sa.ForeignKeyConstraint(['check_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firstname')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('addressone', sa.String(length=20), nullable=True),
    sa.Column('addresstwo', sa.String(length=20), nullable=True),
    sa.Column('apt', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('mobilephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('sinexpire', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('postal', sa.String(length=6), nullable=True),
    sa.Column('trainingid', sa.String(), nullable=True),
    sa.Column('trainingpassword', sa.String(), nullable=True),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.Column('image_file', sa.String(length=50), nullable=True),
    sa.Column('iprismcode', sa.String(length=9), nullable=False),
    sa.Column('mon_avail', sa.String(length=100), nullable=False),
    sa.Column('tue_avail', sa.String(length=100), nullable=False),
    sa.Column('wed_avail', sa.String(length=100), nullable=False),
    sa.Column('thu_avail', sa.String(length=100), nullable=False),
    sa.Column('fri_avail', sa.String(length=100), nullable=False),
    sa.Column('sat_avail', sa.String(length=100), nullable=False),
    sa.Column('sun_avail', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainingid')
    )
    op.create_table('incident_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('empdocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_document', sa.String(length=100), nullable=False),
    sa.Column('file_employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_employee'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee2_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('sig_data', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee2_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['hrfiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completeddate', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staffschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('storeworked', sa.String(), nullable=True),
    sa.Column('shift_description', sa.String(), nullable=True),
    sa.Column('shift_hours', sa.Integer(), nullable=True),
    sa.Column('shift_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffschedule')
    op.drop_table('grade')
    op.drop_table('empfile')
    op.drop_table('empdocs')
    op.drop_table('roles_users')
    op.drop_table('incident_files')
    op.drop_table('employee')
    op.drop_table('customer')
    op.drop_table('checkinout')
    op.drop_table('user')
    op.drop_table('task_store')
    op.drop_table('salt_store')
    op.drop_table('reclaim_store')
    op.drop_table('maintain_store')
    op.drop_table('incident_store')
    op.drop_table('incident')
    op.drop_table('user_activity')
    op.drop_table('twimlmessages')
    op.drop_table('todo')
    op.drop_table('store')
    op.drop_table('saltlog')
    op.drop_table('role')
    op.drop_table('reclaimtank')
    op.drop_table('incidentnumbers')
    op.drop_table('hrfiles')
    op.drop_table('error')
    op.drop_table('cwmaintenance')
    op.drop_table('course')
    op.drop_table('completedfile')
    op.drop_table('company')
    op.drop_table('bulk_email_sendgrid')
    # ### end Alembic commands ###
